config.username=jmdcode
config.name=Juan
config.last-name=Damas
config.code=123456
config.country.name=México
config.country.code=MX
config.list.values=one,two,three,four,five
config.valuesMap={product: "Laptop", price: 1000, stock: true}